"""
Watchmaker's Lathe Controller — Hardware Input
Rotary encoder + physical buttons via GPIO with debouncing.
"""

from __future__ import annotations

import logging
import time
import threading
from enum import Enum, auto
from collections import deque
from typing import Callable, Optional

logger = logging.getLogger(__name__)

try:
    import pigpio
    HAS_PIGPIO = True
except ImportError:
    HAS_PIGPIO = False


class InputEvent(Enum):
    """Events generated by hardware inputs."""
    NONE = auto()
    # Encoder
    ENC_CW = auto()
    ENC_CCW = auto()
    ENC_PRESS = auto()
    ENC_LONG_PRESS = auto()
    # Buttons
    BTN_MODE = auto()
    BTN_MODE_LONG = auto()
    BTN_GO_STOP = auto()
    BTN_GO_STOP_LONG = auto()
    BTN_ESTOP = auto()


class HardwareInput:
    """
    Manages rotary encoder and physical buttons via pigpio callbacks.
    
    Provides an event queue that the main application loop polls.
    The encoder uses gray-code decoding for reliable rotation detection.
    """

    DEBOUNCE_MS = 50
    LONG_PRESS_MS = 1000

    def __init__(self, config):
        self.cfg = config
        self._pi: Optional[pigpio.pi] = None
        self._event_queue = deque(maxlen=64)
        self._lock = threading.Lock()

        # Encoder state
        self._enc_last_state = 0
        self._enc_count = 0
        self._enc_callbacks = []

        # Button states: {pin: {"pressed": bool, "time": float, "long_fired": bool}}
        self._buttons = {}
        self._btn_callbacks = []

        # External event listeners
        self._listeners: list[Callable] = []

    # ================================================================
    # Init / Shutdown
    # ================================================================
    def init(self, pi: pigpio.pi = None):
        """Initialize GPIO inputs."""
        if not HAS_PIGPIO:
            logger.info("[INPUT] Simulation mode — no GPIO")
            return True

        if pi:
            self._pi = pi
        else:
            self._pi = pigpio.pi()
            if not self._pi.connected:
                logger.error("[INPUT] Failed to connect to pigpio")
                return False

        # Encoder pins
        for pin in [self.cfg.gpio.pin_enc_clk, self.cfg.gpio.pin_enc_dt, self.cfg.gpio.pin_enc_sw]:
            self._pi.set_mode(pin, pigpio.INPUT)
            self._pi.set_pull_up_down(pin, pigpio.PUD_UP)
            self._pi.set_glitch_filter(pin, 300)  # 300µs glitch filter

        # Button pins
        for pin in [self.cfg.gpio.pin_btn_mode, self.cfg.gpio.pin_btn_go_stop, self.cfg.gpio.pin_btn_estop]:
            self._pi.set_mode(pin, pigpio.INPUT)
            self._pi.set_pull_up_down(pin, pigpio.PUD_UP)
            self._pi.set_glitch_filter(pin, 1000)  # Heavier filtering for buttons

        # Init encoder state
        a = self._pi.read(self.cfg.gpio.pin_enc_clk)
        b = self._pi.read(self.cfg.gpio.pin_enc_dt)
        self._enc_last_state = (a << 1) | b

        # Register callbacks
        self._enc_callbacks = [
            self._pi.callback(self.cfg.gpio.pin_enc_clk, pigpio.EITHER_EDGE, self._on_encoder),
            self._pi.callback(self.cfg.gpio.pin_enc_dt, pigpio.EITHER_EDGE, self._on_encoder),
        ]

        # Button callbacks
        self._buttons = {
            self.cfg.gpio.pin_enc_sw: {"pressed": False, "time": 0, "long_fired": False,
                                        "short": InputEvent.ENC_PRESS, "long": InputEvent.ENC_LONG_PRESS},
            self.cfg.gpio.pin_btn_mode: {"pressed": False, "time": 0, "long_fired": False,
                                          "short": InputEvent.BTN_MODE, "long": InputEvent.BTN_MODE_LONG},
            self.cfg.gpio.pin_btn_go_stop: {"pressed": False, "time": 0, "long_fired": False,
                                             "short": InputEvent.BTN_GO_STOP, "long": InputEvent.BTN_GO_STOP_LONG},
            self.cfg.gpio.pin_btn_estop: {"pressed": False, "time": 0, "long_fired": False,
                                           "short": InputEvent.BTN_ESTOP, "long": InputEvent.BTN_ESTOP},
        }

        for pin in self._buttons:
            cb = self._pi.callback(pin, pigpio.EITHER_EDGE, self._on_button)
            self._btn_callbacks.append(cb)

        # Start long-press polling thread
        self._polling = True
        self._poll_thread = threading.Thread(target=self._poll_long_press, daemon=True)
        self._poll_thread.start()

        logger.info("[INPUT] Initialized: encoder + 4 buttons")
        return True

    def shutdown(self):
        """Release resources."""
        self._polling = False

        for cb in self._enc_callbacks + self._btn_callbacks:
            cb.cancel()
        self._enc_callbacks.clear()
        self._btn_callbacks.clear()

        logger.info("[INPUT] Shutdown")

    # ================================================================
    # Event Queue
    # ================================================================
    def poll(self) -> InputEvent:
        """Get the next event, or NONE if empty."""
        with self._lock:
            if self._event_queue:
                return self._event_queue.popleft()
        return InputEvent.NONE

    def poll_all(self) -> list:
        """Drain all pending events."""
        with self._lock:
            events = list(self._event_queue)
            self._event_queue.clear()
        return events

    def add_listener(self, callback: Callable):
        """Register a function to be called on every event."""
        self._listeners.append(callback)

    def _push_event(self, event: InputEvent):
        with self._lock:
            self._event_queue.append(event)
        for listener in self._listeners:
            try:
                listener(event)
            except Exception as e:
                logger.error(f"[INPUT] Listener error: {e}")

    # ================================================================
    # Simulated Input (for testing)
    # ================================================================
    def inject_event(self, event: InputEvent):
        """Inject a synthetic event (for testing/simulation)."""
        self._push_event(event)

    # ================================================================
    # Encoder knob position (for speed control)
    # ================================================================
    @property
    def encoder_delta(self) -> int:
        """Get and reset the encoder count since last read."""
        with self._lock:
            delta = self._enc_count
            self._enc_count = 0
        return delta

    # ================================================================
    # Internal: Encoder callback
    # ================================================================
    def _on_encoder(self, gpio, level, tick):
        """Gray-code quadrature decoder."""
        a = self._pi.read(self.cfg.gpio.pin_enc_clk)
        b = self._pi.read(self.cfg.gpio.pin_enc_dt)
        state = (a << 1) | b

        # State transition table
        transitions = {
            (0b00, 0b01): 1,  (0b01, 0b11): 1,
            (0b11, 0b10): 1,  (0b10, 0b00): 1,
            (0b00, 0b10): -1, (0b10, 0b11): -1,
            (0b11, 0b01): -1, (0b01, 0b00): -1,
        }

        key = (self._enc_last_state, state)
        if key in transitions:
            delta = transitions[key]
            with self._lock:
                self._enc_count += delta

            if delta > 0:
                self._push_event(InputEvent.ENC_CW)
            else:
                self._push_event(InputEvent.ENC_CCW)

        self._enc_last_state = state

    # ================================================================
    # Internal: Button callback
    # ================================================================
    def _on_button(self, gpio, level, tick):
        """Button press/release handler."""
        if gpio not in self._buttons:
            return

        btn = self._buttons[gpio]
        now = time.monotonic()

        if level == 0:  # Pressed (active LOW)
            btn["pressed"] = True
            btn["time"] = now
            btn["long_fired"] = False

            # E-STOP is immediate (no waiting for release)
            if btn["short"] == InputEvent.BTN_ESTOP:
                self._push_event(InputEvent.BTN_ESTOP)

        elif level == 1:  # Released
            if btn["pressed"] and not btn["long_fired"]:
                # Short press (skip for E-STOP, already fired)
                if btn["short"] != InputEvent.BTN_ESTOP:
                    self._push_event(btn["short"])
            btn["pressed"] = False

    # ================================================================
    # Internal: Long press polling
    # ================================================================
    def _poll_long_press(self):
        """Check for long presses at 20 Hz."""
        while self._polling:
            now = time.monotonic()
            for pin, btn in self._buttons.items():
                if btn["pressed"] and not btn["long_fired"]:
                    if (now - btn["time"]) >= (self.LONG_PRESS_MS / 1000.0):
                        btn["long_fired"] = True
                        self._push_event(btn["long"])
            time.sleep(0.05)
