#pragma once
// ============================================================================
// Input Module — Header
// Rotary encoder + push buttons with debounce
// ============================================================================

#include <Arduino.h>

/// Input events generated by the input system
enum class InputEvent {
    NONE,
    // Encoder
    ENC_CW,             // Encoder rotated clockwise
    ENC_CCW,            // Encoder rotated counter-clockwise
    ENC_PRESS,          // Encoder button short press
    ENC_LONG_PRESS,     // Encoder button long press
    // Buttons
    BTN_MODE,           // MODE button short press
    BTN_MODE_LONG,      // MODE button long press
    BTN_PRESET,         // PRESET button short press
    BTN_PRESET_LONG,    // PRESET button long press
    BTN_GO,             // GO button short press
    BTN_GO_LONG         // GO button long press (emergency stop)
};

/// Initialize all input pins and interrupts
void input_init();

/// Poll for input events — call every loop iteration
/// Returns the next pending event, or NONE if nothing happened
InputEvent input_poll();

/// Check if a specific button is currently held down
bool input_is_held(uint8_t pin);

/// Get the raw encoder position (cumulative)
long input_get_encoder_raw();

/// Reset the encoder counter
void input_reset_encoder();
